# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20170227_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
